export const API_RESPONSE = {
  data: [
    {
      name: "Mixmax",
      budget_name: "Software subscription",
      owner_id: 1,
      spent: { value: 1000, currency: "SGD" },
      available_to_spend: { value: 1000, currency: "SGD" },
      card_type: "burner",
      expiry: "2026-02-09",
      limit: 100,
      status: "active",
    },
    {
      name: "QuickBooks",
      budget_name: "Software subscription",
      owner_id: 2,
      spent: { value: 50, currency: "SGD" },
      available_to_spend: { value: 250, currency: "SGD" },
      card_type: "subscription",
      limit: 10,
      status: "active",
    },
    {
      name: "Slack",
      budget_name: "Communication",
      owner_id: 3,
      spent: { value: 200, currency: "USD" },
      available_to_spend: { value: 800, currency: "USD" },
      card_type: "subscription",
      limit: 200,
      status: "active",
    },
    {
      name: "AWS",
      budget_name: "Cloud Services",
      owner_id: 4,
      spent: { value: 750, currency: "USD" },
      available_to_spend: { value: 1250, currency: "USD" },
      card_type: "burner",
      expiry: "2026-03-15",
      limit: 1000,
      status: "active",
    },
    {
      name: "Google Ads",
      budget_name: "Marketing",
      owner_id: 5,
      spent: { value: 400, currency: "SGD" },
      available_to_spend: { value: 600, currency: "SGD" },
      card_type: "burner",
      expiry: "2026-04-01",
      limit: 500,
      status: "active",
    },
    {
      name: "Figma",
      budget_name: "Design Tools",
      owner_id: 6,
      spent: { value: 120, currency: "USD" },
      available_to_spend: { value: 380, currency: "USD" },
      card_type: "subscription",
      limit: 100,
      status: "active",
    },
    {
      name: "Notion",
      budget_name: "Productivity",
      owner_id: 7,
      spent: { value: 60, currency: "SGD" },
      available_to_spend: { value: 440, currency: "SGD" },
      card_type: "subscription",
      limit: 50,
      status: "active",
    },
    {
      name: "HubSpot",
      budget_name: "CRM",
      owner_id: 8,
      spent: { value: 300, currency: "USD" },
      available_to_spend: { value: 700, currency: "USD" },
      card_type: "burner",
      expiry: "2026-05-10",
      limit: 500,
      status: "blocked",
    },
    {
      name: "Mailchimp",
      budget_name: "Marketing",
      owner_id: 9,
      spent: { value: 150, currency: "SGD" },
      available_to_spend: { value: 350, currency: "SGD" },
      card_type: "subscription",
      limit: 150,
      status: "active",
    },
    {
      name: "Dropbox",
      budget_name: "Storage",
      owner_id: 10,
      spent: { value: 80, currency: "USD" },
      available_to_spend: { value: 420, currency: "USD" },
      card_type: "subscription",
      limit: 100,
      status: "active",
    },
    {
      name: "Zoom",
      budget_name: "Communication",
      owner_id: 11,
      spent: { value: 95, currency: "SGD" },
      available_to_spend: { value: 405, currency: "SGD" },
      card_type: "subscription",
      limit: 100,
      status: "active",
    },
    {
      name: "Adobe CC",
      budget_name: "Design Tools",
      owner_id: 12,
      spent: { value: 500, currency: "USD" },
      available_to_spend: { value: 1500, currency: "USD" },
      card_type: "burner",
      expiry: "2026-06-01",
      limit: 600,
      status: "active",
    },
    {
      name: "Canva",
      budget_name: "Design Tools",
      owner_id: 13,
      spent: { value: 40, currency: "SGD" },
      available_to_spend: { value: 160, currency: "SGD" },
      card_type: "subscription",
      limit: 50,
      status: "active",
    },
    {
      name: "Stripe",
      budget_name: "Payments",
      owner_id: 14,
      spent: { value: 900, currency: "USD" },
      available_to_spend: { value: 2100, currency: "USD" },
      card_type: "burner",
      expiry: "2026-07-12",
      limit: 1000,
      status: "active",
    },
    {
      name: "Twilio",
      budget_name: "Communication",
      owner_id: 15,
      spent: { value: 250, currency: "USD" },
      available_to_spend: { value: 750, currency: "USD" },
      card_type: "burner",
      expiry: "2026-08-20",
      limit: 300,
      status: "active",
    },
    {
      name: "Asana",
      budget_name: "Project Management",
      owner_id: 16,
      spent: { value: 110, currency: "SGD" },
      available_to_spend: { value: 390, currency: "SGD" },
      card_type: "subscription",
      limit: 120,
      status: "active",
    },
    {
      name: "Trello",
      budget_name: "Project Management",
      owner_id: 17,
      spent: { value: 70, currency: "USD" },
      available_to_spend: { value: 330, currency: "USD" },
      card_type: "subscription",
      limit: 80,
      status: "blocked",
    },
    {
      name: "GitHub",
      budget_name: "Development Tools",
      owner_id: 18,
      spent: { value: 300, currency: "USD" },
      available_to_spend: { value: 700, currency: "USD" },
      card_type: "subscription",
      limit: 300,
      status: "active",
    },
    {
      name: "GitLab",
      budget_name: "Development Tools",
      owner_id: 19,
      spent: { value: 180, currency: "SGD" },
      available_to_spend: { value: 820, currency: "SGD" },
      card_type: "subscription",
      limit: 200,
      status: "active",
    },
    {
      name: "DigitalOcean",
      budget_name: "Cloud Services",
      owner_id: 20,
      spent: { value: 600, currency: "USD" },
      available_to_spend: { value: 1400, currency: "USD" },
      card_type: "burner",
      expiry: "2026-09-10",
      limit: 700,
      status: "active",
    },

    {
      name: "Netflix Ads",
      budget_name: "Marketing",
      owner_id: 21,
      spent: { value: 320, currency: "USD" },
      available_to_spend: { value: 680, currency: "USD" },
      card_type: "burner",
      expiry: "2026-10-01",
      limit: 500,
      status: "expired",
    },
    {
      name: "LinkedIn Ads",
      budget_name: "Marketing",
      owner_id: 22,
      spent: { value: 220, currency: "SGD" },
      available_to_spend: { value: 780, currency: "SGD" },
      card_type: "burner",
      expiry: "2026-11-11",
      limit: 400,
      status: "active",
    },
    {
      name: "Firebase",
      budget_name: "Cloud Services",
      owner_id: 23,
      spent: { value: 410, currency: "USD" },
      available_to_spend: { value: 590, currency: "USD" },
      card_type: "subscription",
      limit: 500,
      status: "active",
    },
    {
      name: "MongoDB Atlas",
      budget_name: "Database",
      owner_id: 24,
      spent: { value: 260, currency: "USD" },
      available_to_spend: { value: 740, currency: "USD" },
      card_type: "subscription",
      limit: 300,
      status: "active",
    },
    {
      name: "Heroku",
      budget_name: "Cloud Services",
      owner_id: 25,
      spent: { value: 150, currency: "SGD" },
      available_to_spend: { value: 350, currency: "SGD" },
      card_type: "burner",
      expiry: "2026-12-15",
      limit: 200,
      status: "blocked",
    },
    {
      name: "PayPal",
      budget_name: "Payments",
      owner_id: 26,
      spent: { value: 800, currency: "USD" },
      available_to_spend: { value: 1200, currency: "USD" },
      card_type: "burner",
      expiry: "2027-01-01",
      limit: 900,
      status: "active",
    },
    {
      name: "Razorpay",
      budget_name: "Payments",
      owner_id: 27,
      spent: { value: 540, currency: "SGD" },
      available_to_spend: { value: 460, currency: "SGD" },
      card_type: "burner",
      expiry: "2026-06-30",
      limit: 600,
      status: "active",
    },
    {
      name: "Zoho CRM",
      budget_name: "CRM",
      owner_id: 28,
      spent: { value: 210, currency: "SGD" },
      available_to_spend: { value: 290, currency: "SGD" },
      card_type: "subscription",
      limit: 250,
      status: "active",
    },
    {
      name: "Calendly",
      budget_name: "Productivity",
      owner_id: 29,
      spent: { value: 30, currency: "USD" },
      available_to_spend: { value: 170, currency: "USD" },
      card_type: "subscription",
      limit: 50,
      status: "cancelled",
    },
    {
      name: "Intercom",
      budget_name: "Customer Support",
      owner_id: 30,
      spent: { value: 370, currency: "USD" },
      available_to_spend: { value: 630, currency: "USD" },
      card_type: "burner",
      expiry: "2026-08-08",
      limit: 400,
      status: "active",
    },
    {
      name: "Zendesk",
      budget_name: "Customer Support",
      owner_id: 31,
      spent: { value: 290, currency: "SGD" },
      available_to_spend: { value: 710, currency: "SGD" },
      card_type: "subscription",
      limit: 300,
      status: "active",
    },
    {
      name: "Shopify",
      budget_name: "E-commerce",
      owner_id: 32,
      spent: { value: 600, currency: "USD" },
      available_to_spend: { value: 1400, currency: "USD" },
      card_type: "burner",
      expiry: "2026-07-07",
      limit: 700,
      status: "active",
    },
    {
      name: "WooCommerce",
      budget_name: "E-commerce",
      owner_id: 33,
      spent: { value: 140, currency: "SGD" },
      available_to_spend: { value: 360, currency: "SGD" },
      card_type: "subscription",
      limit: 200,
      status: "active",
    },
    {
      name: "Hotjar",
      budget_name: "Analytics",
      owner_id: 34,
      spent: { value: 90, currency: "USD" },
      available_to_spend: { value: 410, currency: "USD" },
      card_type: "subscription",
      limit: 100,
      status: "active",
    },
    {
      name: "Amplitude",
      budget_name: "Analytics",
      owner_id: 35,
      spent: { value: 500, currency: "USD" },
      available_to_spend: { value: 1500, currency: "USD" },
      card_type: "burner",
      expiry: "2026-05-05",
      limit: 600,
      status: "active",
    },
    {
      name: "ClickUp",
      budget_name: "Project Management",
      owner_id: 36,
      spent: { value: 160, currency: "SGD" },
      available_to_spend: { value: 340, currency: "SGD" },
      card_type: "subscription",
      limit: 200,
      status: "active",
    },
    {
      name: "Monday.com",
      budget_name: "Project Management",
      owner_id: 37,
      spent: { value: 210, currency: "USD" },
      available_to_spend: { value: 790, currency: "USD" },
      card_type: "subscription",
      limit: 250,
      status: "blocked",
    },
    {
      name: "SendGrid",
      budget_name: "Communication",
      owner_id: 38,
      spent: { value: 180, currency: "USD" },
      available_to_spend: { value: 820, currency: "USD" },
      card_type: "burner",
      expiry: "2026-09-09",
      limit: 300,
      status: "active",
    },
    {
      name: "Postman",
      budget_name: "Development Tools",
      owner_id: 39,
      spent: { value: 75, currency: "SGD" },
      available_to_spend: { value: 225, currency: "SGD" },
      card_type: "subscription",
      limit: 100,
      status: "active",
    },
    {
      name: "Linear",
      budget_name: "Development Tools",
      owner_id: 40,
      spent: { value: 130, currency: "USD" },
      available_to_spend: { value: 370, currency: "USD" },
      card_type: "subscription",
      limit: 150,
      status: "active",
    },
  ],
  page: 1,
  per_page: 40,
  total: 100,
};
